<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc" style="margin-top: 1em;"><ul class="toc-item"></ul></div>

In [1]:
from scipy.special import comb
import itertools

NUM_SYMBOL = 64
NUM_CHIP = 8
NUM_PLANE = 2
NUM_SIB = NUM_SYMBOL // ( NUM_CHIP * NUM_PLANE )
NUM_BLK = 10
numcor = 1

In [10]:
cc_tbl = [ [[1,1,1],[]], [[10],[1,2,3]], [[3],[3,3,3]], [[1,2,3],[2]] ] 

In [11]:
def get_cyc_list( bb_chip, cc_tbl ):
    ret = []
    for chip in bb_chip:
        ret.append( cc_tbl[chip][0] )
        ret.append( cc_tbl[chip][1] )
    return ret

In [23]:
def get_cyc_mat( cyc_list, ncyc ):
    xx = np.zeros( (ncyc,len(cyc_list)), dtype=int)
    for i,cyc in enumerate(cyc_list):
        for j in cyc:
            xx[j,i] += 1
    return xx
    

In [ ]:
np.all( np.sum( xx, axis=1 ) <= 1 )

In [125]:
def get_lib_list( uc_mat, num_blk, num_sib ):
    ret = []
    for ucl in uc_mat:
        lst = [] 
        for num_uc in ucl:
            lst += list( np.random.choice(num_blk,num_uc, replace=False ) // num_sib )
        ret.append( lst)
    return ret
    

In [222]:
def check_unc( lib_list ):
    for lib in lib_list:
        if len(lib) != len(set(lib)):
            return True
    return False

In [312]:
def go():
    bb_chip = [0,2]
    cyc_list = get_cyc_list( bb_chip, cc_tbl )
    cyc_mat = get_cyc_mat( cyc_list, ncyc = 12 )
    uc_mat = cyc_mat[ np.sum( cyc_mat, axis=1) > 1 ]
    lib_list = get_lib_list( uc_mat, num_blk=NUM_BLK, num_sib=4)
    stat = check_unc( lib_list )
    print( bb_chip)
    print( cyc_list )
    print(cyc_mat)
    print(uc_mat)
    print(lib_list)
    print(stat)

In [290]:
run()

[0, 2]
[[1, 1, 1], [], [3], [3, 3, 3]]
[[0 0 0 0]
 [3 0 0 0]
 [0 0 0 0]
 [0 0 1 3]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[3 0 0 0]
 [0 0 1 3]]
[[22, 17, 20], [2, 24, 10, 19]]
False
